CREATE TABLE IF NOT EXISTS pharmacies (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  pharmacy_id BIGINT NOT NULL REFERENCES pharmacies(id) ON DELETE RESTRICT,
  name VARCHAR(150) NOT NULL,
  last_name VARCHAR(150) NOT NULL,
  date_of_birth DATE NOT NULL,
  prescription TEXT,
  dosage TEXT,
  prescription_ready BOOLEAN NOT NULL DEFAULT FALSE,
  address TEXT,
  phone_number VARCHAR(30)
);
